---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: docker-cluster
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true

node.store.allow_mmap: false

xpack.security.authc.token.enabled: true
discovery.type: single-node
node.name: elasticsearch

logger.org.elasticsearch.xpack.security.authc.oidc: TRACE

xpack.security.authc.realms.oidc.stroke:
  order: 2
  rp.client_id: "michal"
  rp.response_type: code
  rp.redirect_uri: "https://localhost:5601/api/security/oidc/callback"
  op.issuer: "https://auth.dev.qualityregistry.org/realms/stroke"
  op.authorization_endpoint: "https://auth.dev.qualityregistry.org/realms/stroke/protocol/openid-connect/auth"
  op.token_endpoint: "https://auth.dev.qualityregistry.org/realms/stroke/protocol/openid-connect/token"
  op.jwkset_path: "https://auth.dev.qualityregistry.org/realms/stroke/protocol/openid-connect/certs"
  op.userinfo_endpoint: "https://auth.dev.qualityregistry.org/realms/stroke/protocol/openid-connect/userinfo"
  op.endsession_endpoint: "https://auth.dev.qualityregistry.org/realms/stroke/protocol/openid-connect/logout"
  rp.post_logout_redirect_uri: "https://localhost:5601/logged_out"
  claims.principal: name
  ssl.verification_mode: none
